# Generated by Django 5.1.1 on 2024-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_candidate_email_alter_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
